story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', include('story_7.urls')),
    path('about/', include('story_8.urls')),
    path('books/', include('story_9.urls')),
    path('', include('story_10.urls')),
]

story_10/urls.py
from django.urls import path
from story_10 import views

app_name = 'story_10'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.status, name='status'),
    path('confirm/', views.confirm, name='confirm'),
    path('<int:index>/', views.change, name='change'),
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.about, name='about'),
]

story_9/urls.py
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
    path('', views.books, name='books'),
    path('create-book/', views.create_book, name='create_book'),
    path('add-like/', views.add_like, name='add_like'),
    path('top/', views.top, name='top'),
]

story_10/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    image = models.TextField(blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

story_7/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	nama = models.CharField('Name', max_length=20)
	pesan = models.TextField('Message', max_length=280)
	warna = models.CharField('Color', max_length=8, null=True)

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
	id = models.CharField('Id', max_length=200, primary_key=True)
	cover = models.CharField('Cover', max_length=200)
	title = models.CharField('Title', max_length=200)
	author = models.CharField('Author', max_length=200)
	publisher = models.CharField('Publisher', max_length=200)
	publishedDate = models.CharField('Published Date', max_length=200)
	likes = models.PositiveIntegerField('Likes')

story_7/forms.py
from django.forms import ModelForm
from .models import Status

class StatusForm(ModelForm):
	class Meta :
		model = Status
		fields = ['nama', 'pesan']

story_10/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
	return render(request, 'home.html')

def sign_up(request):
	if request.method == 'POST':
	    username = request.POST['username']
	    email = request.POST['email']
	    password = request.POST['password']
	    if User.objects.filter(username=username).exists():
	    	messages.error(request, 'Username is not available!')
	    else:
	    	user = User.objects.create_user(username, email, password)
	    	return redirect('/login')

	return render(request, 'signup.html')

def log_in(request):
	if request.method == 'POST':
	    username = request.POST['username']
	    password = request.POST['password']
	    if User.objects.filter(username=username).exists():
		    user = authenticate(request, username=username, password=password)
		    if user is not None:
		        login(request, user)
		        return redirect('/')
		    else:
		    	messages.error(request, 'Wrong password!')
	    else:
	    	messages.error(request, 'Wrong username!')
	
	return render(request, 'login.html')

def log_out(request):
	logout(request)
	return redirect('/')

def profile(request):
	if request.method == 'POST':
		user = User.objects.get(pk=request.POST['id'])
		user.username = request.POST['username']
		user.email = request.POST['email']
		user.profile.bio = request.POST['bio']
		user.profile.image = request.POST['image']
		user.save()
		return redirect('/')

	return render(request, 'update.html')

story_7/views.py
from django.shortcuts import render, redirect
import random
from .models import Status
from .forms import StatusForm

# Create your views here.
def status(request):
	if request.method == 'POST':
		nama = request.POST['nama']
		pesan = request.POST['pesan']
		red = str(hex(random.randint(0, 255)))[2:]
		green = str(hex(random.randint(0, 255)))[2:]
		blue = str(hex(random.randint(0, 255)))[2:]
		warna = '#' + red + green + blue
		Status.objects.create(nama=nama, pesan=pesan, warna=warna)

	status_list = Status.objects.all()
	form = StatusForm()

	context = {
		'status': status_list,
		'form' : form
	}
	return render(request, 'status.html', context=context)

def change(request, index):
	status = Status.objects.get(pk=index)
	warna = status.warna

	while status.warna == warna :
		red = str(hex(random.randint(0, 255)))[2:]
		green = str(hex(random.randint(0, 255)))[2:]
		blue = str(hex(random.randint(0, 255)))[2:]
		warna = '#' + red + green + blue

	status.warna = warna
	status.save()

	return redirect('/status/')

def confirm(request):
	if request.method == 'POST':
		form = StatusForm(request.POST)
		context = {
			'nama' : form.data['nama'],
	        'pesan' : form.data['pesan']
	        }
		return render(request, 'confirm.html', context=context)

story_8/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
	return render(request, 'about.html')

story_9/views.py
from django.forms.models import model_to_dict
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseForbidden
from .models import Book

# Create your views here.
def books(request) :
	return render(request, 'books.html')

@csrf_exempt
def create_book(request) :
	if(request.is_ajax()) :
		data = {}
		if(Book.objects.filter(id=request.POST['id']).exists()) :
			existing_book = Book.objects.get(id=request.POST['id'])
			data['likes'] = existing_book.likes
		else :
			data['likes'] = 0
			Book.objects.create(
	            id=request.POST['id'],
	            cover=request.POST['cover'],
	            title=request.POST['title'],
	            author=request.POST['author'],
	            publisher=request.POST['publisher'],
	            publishedDate=request.POST['publishedDate'],
	            likes=0
	        )
		return JsonResponse(data)
	else :
		return HttpResponseForbidden()

@csrf_exempt
def add_like(request) :
	if(request.is_ajax()) :
		book = Book.objects.get(id=request.POST['id'])
		book.likes += 1
		book.save()
		data = {'likes' : book.likes}
		return JsonResponse(data)
	else :
		return HttpResponseForbidden()

def top(request) :
	if(request.is_ajax()) :
		top5 = [model_to_dict(book) for book in Book.objects.order_by('-likes')[:5]]
		return JsonResponse({'items':top5})
	else :
		return HttpResponseForbidden()

story_10/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 10 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="home">
  {% if user.is_authenticated %}
    <div class="title"> Hi {{ user.username }}! </div>
    <div class=""> {{ user.profile.bio }} </div>
    <img src="{{ user.profile.image }}">
    <br>
    <br>
    <div class=""> Update your profile here </div>
    <a href="{% url 'story_10:profile' %}" class="btn btn-primary" name="profile">Update Profile</a>
    <div class=""> Want to log out? </div>
    <a href="{% url 'story_10:logout' %}" class="btn btn-primary" name="logout">Log Out</a>

  {% else %}
    <div class="title"> WELCOME </div>
    <div class=""> Don't have an account? Sign up here </div>
    <a href="{% url 'story_10:signup' %}" class="btn btn-primary" name="signup">Sign Up</a>
    <div class=""> Already have an account? Login here </div>
    <a href="{% url 'story_10:login' %}" class="btn btn-primary" name="login">Log In</a>
  {% endif %}
</section>
{% endblock %}

story_10/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 10 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="login" style="background-color:white">
  {% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
		<h2> Hi {{ user.username }}! </h2>
    <p> You have already logged in </p>
    <a href="{% url 'story_10:home' %}" class="btn btn-primary">Back to Home</a>
  {% else %}
    <div class="section-title"> Log In </div>

    <form action="" method="POST">
	    {% csrf_token %}
	    <table class="table my-3" style="width:50vw">
		    <tr>
		    	<colgroup>
	      	<col span="1" style="width: 30%;">
	       	<col span="1" style="width: 10%;">
	       	<col span="1" style="width: 60%;">

		      <td> Username </td>
		      <td> : </td>
		      <td> <input id="username" name="username" type="text" required> </td>
		    </tr>

		    <tr>
		      <td> Password </td>
		      <td> : </td>
		      <td> <input id="password" name="password" type="password" required> </td>
		    </tr>

		  </table>
		  <input type="submit" value="Log In" class="btn btn-primary" id="login">
	  </form>

	  <br>
	  <div> 
	  	Don't have an account? Sign up
    	<a href="{% url 'story_10:signup' %}"> here </a>
	  </div>
  {% endif %}
</section>
{% endblock %}

story_10/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 10 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="signup" style="background-color:white">
	{% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
  	<h2> Hi {{ user.username }}! </h2>
    <p> You have already logged in </p>
    <p> Log Out to create a new account </p>
    <a href="{% url 'story_10:home' %}" class="btn btn-primary">Back to Home</a>
    <a href="{% url 'story_10:logout' %}" class="btn btn-primary">Log Out</a>
  {% else %}
    <div class="section-title "> Sign Up </div>

    <form action="" method="POST">
	    {% csrf_token %}
	    <table class="table my-3" style="width:50vw">
    		<colgroup>
      	<col span="1" style="width: 30%;">
       	<col span="1" style="width: 10%;">
       	<col span="1" style="width: 60%;">

		    <tr>
		      <td> Username </td>
		      <td> : </td>
		      <td> <input id="username" name="username" type="text" required> </td>
		    </tr>

		    <tr>
		      <td> Email </td>
		      <td> : </td>
		      <td> <input id="email" name="email" type="email" required> </td>
		    </tr>

		    <tr>
		      <td> Password </td>
		      <td> : </td>
		      <td> <input id="password" name="password" type="password" required> </td>
		    </tr>

		  </table>
		  <input type="submit" value="Sign Up" class="btn btn-primary" id="signup">
	  </form>

	 	<br>
	  <div> 
	  	Already have an account? Log in 
    	<a href="{% url 'story_10:login' %}"> here </a>
	  </div>
  {% endif %}
</section>
{% endblock %}

story_10/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 10 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="signup" style="background-color:white">
	{% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
    <div class="section-title "> Update Profile </div>
  	<h2> Hi {{ user.username }}! </h2>

    <form action="" method="POST">
	    {% csrf_token %}
	    <table class="table my-3" style="width:50vw">
    		<colgroup>
      	<col span="1" style="width: 30%;">
       	<col span="1" style="width: 10%;">
       	<col span="1" style="width: 60%;">

		    <tr>
		      <td> Username </td>
		      <td> : </td>
		      <td> <input id="username" name="username" type="text" value="{{user.username}}" required> </td>
		    </tr>

		    <tr>
		      <td> Email </td>
		      <td> : </td>
		      <td> <input id="email" name="email" type="email" value="{{user.email}}" required> </td>
		    </tr>

		    <tr>
		      <td> Bio </td>
		      <td> : </td>
		      <td> <input id="bio" name="bio" type="text" value="{{user.profile.bio}}"> </td>
		    </tr>

		    <tr>
		      <td> Profile Picture </td>
		      <td> : </td>
		      <td> <input id="image" name="image" type="text" value="{{user.profile.image}}"> </td>
		    </tr>

		  </table>
		  <input type="hidden" name="id" value="{{ user.id }}">
		  <input type="submit" value="Update Profile" class="btn btn-primary" id="update">
	  </form>
  {% else %}
  	<h2> You haven't logged in yet </h2>
    <p> Log in to update your profile </p>
    <a href="{% url 'story_10:login' %}" class="btn btn-primary">Login</a>
  {% endif %}
</section>
{% endblock %}

story_7/templates/confirm.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Are You Sure? {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section>
   <h1 class="section-title"> Are you sure? </h1>

   <p> Are you sure that you want to input this data? </p>
   <table class="table table-bordered">
      <tr>
         <td> Name </td>
         <td> {{ nama }} </td>
      <tr>
         <td> Message </td>
         <td> {{ pesan }} </td>
      </tr>
   </table>

   <form action="{% url 'story_7:status' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="nama" value="{{ nama }}">
      <input type="hidden" name="pesan" value="{{ pesan }}">
      <input class="btn btn-primary d-flex m-auto click" type="submit" id="yes" value="Yes">
   </form>

   <form action="{% url 'story_7:status' %}" method="GET">
       <input class="btn btn-primary d-flex mx-auto click" type="submit" id="no" value="No">
   </form>
</section>
{% endblock %}

story_7/templates/status.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 7 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section>
   <div class="section-title"> STATUS </div>

   {% for x in status %}
   <div class="card-group py-3">
     <div class="card" style="background-color: {{ x.warna }}">
       <div class="card-body">
         <h4 class="card-title"> {{ x.nama }} </h4>
         <p class="card-text"> {{ x.pesan }} </p>
         <a href="{{ x.id }}" class="click btn btn-primary" name="change"> Change Color </a>
       </div>
     </div>
   </div>
   {% endfor %}
</section>

<section>
   <div class="section-title"> Post your message(s) here! </div>
   <form action="confirm/" method="post" validate>
      {% csrf_token %}
      <table class="table mx-5" style="width:90vw">
         {{ form.as_table }}
         <tr>
            <td>&nbsp;</td>
            <td><input id="submit" type="submit" value="Submit" class="btn btn-primary click"></td>
         </tr>
      </table>
   </form>
</section>
{% endblock %}

story_8/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 8 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section class="normal">
  <div class="section-title"> ABOUT ME </div>

  <div class="accordion-container">
    <div id="activity" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Current Activity 
        <div>
          <button class="up"> Up </button>
          <button class="down"> Down </button>
        </div>
      </a>

      <div class="content">
        <p> Still trying to finish ton of assignments everyday </p>
      </div>
    </div>

    <div id="experience" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Experience
        <div>
          <button class="up"> Up </button>
          <button class="down"> Down </button>
        </div>
      </a>

      <div class="content">
        <p> Currently serving as the Head of Relation Division of DPM Fasilkom UI </p>
      </div>
    </div>
    
    <div id="achievement" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Achievement
        <div>
          <button class="up"> Up </button>
          <button class="down"> Down </button>
        </div>
      </a>

      <div class="content">
        <p> I don't think I've achieved anything since I entered college </p>
      </div>
    </div>
    
    <div id="contact" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Contact
        <div>
          <button class="up"> Up </button>
          <button class="down"> Down </button>
        </div>
      </a>

      <div class="content">
        <p> You can contact me at fairuza.raryasdya@ui.ac.id </p>
      </div>
    </div>
  </div>
</section>

<button class="theme ml-3 mb-3 fixed-bottom"> Change Theme </button>
{% endblock %}

{% block script %}  <script src="{% static 'js/accordion.js' %}"></script> {% endblock %}

story_9/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 9 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="book" style="background-color:white">
  <div class="section-title"> BOOKS </div>

  <input type="text" name="search" id="search" placeholder="Search Books" class="form-control" />
  <ul class="list-group" id="list_result"> </ul>
  <button id="top" class="my-3" data-toggle="modal" data-target="#Modal"> Show Top 5 </button>
  <table class="table my-3" id="result"></table>
  

  <div class="modal fade modal-lg" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="section-title" id="ModalLabel" style="padding:0px;"> Top 5 </h5>
        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        	</button>
        </div>

        <div class="modal-body">
        	<table class="table my-3">
          	<thead class="align-middle text-center font-weight-bold">
							<tr>
								<th> Cover </th>
								<th> Title </th>
								<th> Author </th>
								<th> Likes </th>
							</tr>
						</thead>
						<tbody id="top-table"> </tbody>
        	</table>
        </div>
    	</div>
    </div>
  </div>
</section>
{% endblock %}

{% block script %}  
<script src="{% static 'js/books.js' %}"></script> 
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/new-style.css' %}">
        {% block style %}{% endblock %}

        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet"> 
        
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

templates/navbar.html
<div class="dropdown fixed-top">
  <button class="btn btn-secondary dropdown-toggle mt-0 ml-4 pl-3 pr-3"
          type="button" id="dropdownMenu1" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'story_7:status' %}">Story 7</a>
    <a class="dropdown-item" href="{% url 'story_8:about' %}">Story 8</a>
    <a class="dropdown-item" href="{% url 'story_9:books' %}">Story 9</a>
    <a class="dropdown-item" href="{% url 'story_10:home' %}">Story 10</a>
  </div>
</div>